# Generated by Django 5.2.6 on 2025-10-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_alter_coffee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coffee/'),
        ),
    ]
